### ISSUE TITLE
Undefined response

### ISSUE THREAD

**Issue by onanov** [julianh2o/RokuAlexaLambdaSkill#13]
Hi

I have got it all set up and double checked all the IP and port settings, but when I test it I just get a response " there was a problem with the response from this this skill" 

Using test in the alexa skill setup, the response is "Undefined"

Can you suggest what I may be doing wrong?

I am in the U.K. So have it set up English UK - I had to remove the search functionality, as this was throwing an error "literal not defined for your local" - not sure if that may be cUsing an issue - should it work in the U.K.?

**Comment by julianh2o** [comment]
What intent invocation are you using? (what are you saying to Alexa) Seems like somehow there's an error processing your voice command on the lambda side.

**Comment by onanov** [comment]
Hi

Invocation is "tell Roku to ..." e.g. "Tell roku to go home",

Though if I say something random "tell roku to make tea" for example I get the same response, so you could be right

Duncan

Hope that helps

Duncan

**Comment by onanov** [comment]
I did have to edit the intent schema and sample utterances to remove the now deprecated literal slot type. Rather than deleting these can you suggest an alternative slot type that could be used in place of literal?

**Comment by onanov** [comment]
I have now sorted this. It seemed to be an issue with the lambda function. I deleted this and recreated it and it is now working perfectly - Brilliant script - well done
