### ISSUE TITLE
Missing parenthesis in Lamda index.js file

### ISSUE THREAD

**Issue by mbelkin** [julianh2o/RokuAlexaLambdaSkill#2]
I noticed there's a missing parenthesis in the index.js file of the Lamda Skill (line 3) which causes an error. I added in the closing parenthesis and it all works now.

Thanks for your work on this!!

**Comment by julianh2o** [comment]
Thanks! I've also added prev episode and next episode functionality.. as I was finding it a common operation for me at home :)
