### ISSUE TITLE
roku not responding

### ISSUE THREAD

**Issue by jammin1120** [julianh2o/RokuAlexaLambdaSkill#20]
Hello-

great tutorial, trying to move this server from a windows system to my linux server.  Got the node server running, it discovered my roku, however when i make an alexis requests, the roku does not repsond.  the server shows the request going through (Unknown request URL:  /roku/netflix).

any suggestions?

**Comment by jammin1120** [comment]
this is the top portion of my server.js

var serverinfo = require("./serverinfo");
var rokuChannel = require("./rokuchannels");
var http = require('http');
var fs = require('fs');
var urllib = require("url");
var Client = require('node-ssdp').Client;
var dgram = require('dgram');
var ssdp = new Client();

var keyDelay = 100; //typing delay in ms. If you have a faster roku, you can probably reduce this, slower ones may have to increase it.

//null will cause the server to discover the Roku on startup, hard coding a value will allow for faster startups
// When manually setting this, include the protocol, port, and trailing slash eg:
exports.rokuAddress = "http://192.168.1.153:8060/";
var rokuAddress = "http://192.168.1.153:8060/";
var PORT=80;

**Comment by julianh2o** [comment]
You might need to pull the recent changes to RokuLambda/index.js and reupload them. A collaborator made a change to how launching Netflix works, now you use something like `/roku/launch` with the channel as a POST parameter.

**Comment by jammin1120** [comment]
Thank you I will check the POST commands.  To be clear, multiple commands didnt work, ie home, hulu, etc.

I did notice there were changes to most of the files even since I setup my first server a week or two ago. Thank you for the quick response and for keeping your projects current.

**Comment by jammin1120** [comment]
I loaded the server.js file from my old server to the new server and that fixed the problem.  I am not sure if the newest versions will all work together though.  Thanks

**Comment by julianh2o** [comment]
Great, glad you worked it out! It's possible that there's something broken since the last merge
