### ISSUE TITLE
Running a Node Service (Forever)

### ISSUE THREAD

**Issue by cmon69** [julianh2o/RokuAlexaLambdaSkill#28]
I haven't looked real deep into this but am wondering if I can use "forever" in my raspberry pi3 to automatically run my node server "node server.js". It would be nice if I lose power or reboot my pi to have node server.js to run automatically? rather then having to log into my raspberry pi and opening Terminal and typing in node server.js. If this can be done, is anyone got any idea where is should start first?

**Comment by julianh2o** [comment]
Yup, that's how I run this project! It just needs a little configuration to
locate the executable and the log files.

**Comment by cmon69** [comment]
That was actually pretty easy! Thank you julianh2o!
Installed forever and added line to rc.local.
rebooted pi to make sure it works, and it does!
