### ISSUE TITLE
ToggleTV commands

### ISSUE THREAD

**Issue by spreadred** [julianh2o/RokuAlexaLambdaSkill#6]
I assume these commands only work on RokuTVs?

**Comment by julianh2o** [comment]
Which ToggleTV commands are you referring to? I've never owned a RokuTV and have been toggling my TV using a different automated system.

**Comment by spreadred** [comment]
The ToggleTV intent from IntentSchema.json which seems to be handled in the lambda function, but not in the control server.

**Comment by julianh2o** [comment]
Ahh, yes.. that's vestigial. I'll remove it. The project I originally extracted this from had a hack in there to use an IR blaster to control the TV.
