### ISSUE TITLE
SSDP Incorrectly Identifies Hue Bridge as Roku Device

### ISSUE THREAD

**Issue by spreadred** [julianh2o/RokuAlexaLambdaSkill#7]
When allowing SSDP to search for Rokus on my network, it incorrectly identifies my Philips Hue Bridge (Generation 1) as a Roku device.

**Comment by julianh2o** [comment]
Hmm, interesting. I wonder if node-ssdp isn't correctly filtering for the "roku:ecp" identifier or if possibly the hub is responding incorrectly to the broadcast.

I don't have the time to investigate right now, but if you come up with a solution submit a PR and I'll merge it in.

**Comment by mikehobi** [comment]
I have this same issue. I ended up adding an extra check to the ssdp response call.

```
//handle the ssdp response when the roku is found
ssdp.on('response', function (headers, statusCode, rinfo) {
    if ( headers.ST === 'roku:ecp' ) {
        rokuAddress = headers.LOCATION;
        console.log("Found Roku: ", rokuAddress);
    }
});
```

It's a little redundant, but the `ssdp.search()` doesn't appear to be reliable.

**Comment by julianh2o** [comment]
Hey @mikehobi, that looks good! Would you mind submitting a pull request for that change?

**Comment by spreadred** [comment]
Thanks @mikehobi

**Comment by mikehobi** [comment]
No problem!
